# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
logo: "/assets/images/logo.png"
title: Peer Tutoring Center Resources Page
subtitle: "Developed by the NCVirtual Peer Tutoring Center"
email:
description: >- # this means to ignore newlines until "baseurl:"
  The official resource page of the NCVirtual Peer Tutoring Center.
twitter_username: ncvps_ptc
github_username: username
minimal_mistakes_skin: dirt

after_footer_scripts:
 - https://kkv4my7nbhv3.statuspage.io/embed/script.js

search: true
search_provider: algolia

algolia:
  application_id: F7OL26MPPT
  index_name: ptcresources_index
  search_only_api_key: 7ce24efec63b78b3b6e354591a6ab516
  powered_by: true
  
  settings:
    searchableAttributes:
      - title
      - headings
      - unordered(content)
      - unordered(tags)
      - unordered(author)
      - collection,categories,tags
      - unordered(html)
      - unordered(excerpt_html)
    attributesToHighlight:
      - author
      - author_profile
      - categories
      - content
      - excerpt_html
      - excerpt_text
      - headings
      - html
      - tags
      - title
      - url



# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - social-share

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: [vendor]
# Plugins (previously gems:)

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name   : "First Lastname"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Peer Tutoring Center Homepage"
      icon: "far fa-window-restore"
      url: "https://ncvps.org/peer-tutoring-center/"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/ncvps_ptc/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ncvps_ptc"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/NCVPSPTC/
    - label: "Statuspage"
      icon: "fas fa-check-square"
      url: https://ptcresourcespage.statuspage.io/
    - label: "Issue Reporting System"
      icon: "fas fa-exclamation-circle"
      url: https://docs.google.com/forms/d/e/1FAIpQLSfWc-u_uYDdN7EgfFwTt4NRPPAJ889JUzeG2vR5fp1BI9nhzA/viewform?usp=sf_link

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

